"""
Deterministic GSIS Financial & Actuarial Calculators (Zero LLM Mental Math)
===========================================================================
Implements:
  - PPG No. 393-23: Multi-Purpose Loan (MPL) Flex & Reloan Offset Calculator
  - Republic Act No. 8291: Basic Monthly Pension (BMP), Option 1 (60x) vs Option 2 (18x)
"""

from typing import Dict, Any, List, Optional

OFFICIAL_TENTATIVE_DISCLAIMER = (
    "⚠️ OFFICIAL GSIS DISCLAIMER: This is a tentative deterministic computation generated by GSIS Gabay AI "
    "based on posted Electronic Remittance Files (ERF) and active loan ledgers. Final net proceeds and "
    "retirement benefits are subject to Agency Authorized Officer (AAO) certification and final GSIS audit."
)

COMING_SOON_ACTIONS = {
    "mpl_flex_apply": {
        "action_id": "mpl_flex_apply",
        "label": "Submit MPL Flex Application",
        "badge": "Coming Soon!",
        "description": (
            "Direct 1-click MPL Flex Loan Application write-back to SAP Loans Management & AAO eBCS Certification "
            "is scheduled for Phase 3 Production Rollout with step-up biometric confirmation."
        ),
    },
    "apir_schedule": {
        "action_id": "apir_schedule",
        "label": "Schedule APIR Video Interview",
        "badge": "Coming Soon!",
        "description": (
            "Interactive APIR facial biometrics enrollment and live video interview booking inside chat "
            "is scheduled for Phase 3 Production Rollout."
        ),
    },
    "erf_reconciliation": {
        "action_id": "erf_reconciliation",
        "label": "File ERF Reconciliation Ticket",
        "badge": "Coming Soon!",
        "description": (
            "Automated Electronic Remittance File (ERF) reconciliation ticket routing to your Agency Authorized "
            "Officer (AAO) and GSIS Billing & Collection Unit is scheduled for Phase 3 Production Rollout."
        ),
    },
}


def simulate_mpl_flex_reloan(
    basic_monthly_salary: float,
    ppp_years: float,
    requested_amount: Optional[float] = None,
    requested_term_months: int = 84,
    existing_loans: Optional[List[Dict[str, Any]]] = None,
    current_net_take_home_pay: Optional[float] = None,
) -> Dict[str, Any]:
    """
    Deterministically computes MPL Flex entitlement, existing loan offset,
    2% service fee, MRI fee, net proceeds, and GAA PHP 5,000 net pay check.
    """
    existing_loans = existing_loans or []
    if ppp_years < 0.5:
        multiplier = 0
    elif ppp_years < 3.0:
        multiplier = 4
    elif ppp_years < 5.0:
        multiplier = 8
    elif ppp_years < 10.0:
        multiplier = 10
    else:
        multiplier = 14

    max_entitlement = min(5_000_000.0, round(basic_monthly_salary * multiplier, 2))
    gross_loan = max_entitlement
    if requested_amount and 10_000.0 <= requested_amount <= max_entitlement:
        gross_loan = round(requested_amount, 2)

    annual_rate = 0.06 if ppp_years >= 3.0 else 0.07
    monthly_rate = annual_rate / 12.0
    term_months = max(12, min(84, int(requested_term_months)))

    if gross_loan > 0:
        new_amort = round(
            gross_loan
            * (monthly_rate * ((1 + monthly_rate) ** term_months))
            / (((1 + monthly_rate) ** term_months) - 1),
            2,
        )
    else:
        new_amort = 0.0

    offset_types = {"MPL_FLEX", "CONSO_LOAN", "MPL_LITE", "SALARY_LOAN"}
    offset_loans = [
        l for l in existing_loans if l.get("loan_status") == "ACTIVE" and l.get("loan_type") in offset_types
    ]
    outstanding_offset = round(sum(float(l.get("outstanding_balance", 0.0)) for l in offset_loans), 2)
    replaced_amort = round(sum(float(l.get("monthly_amortization", 0.0)) for l in offset_loans), 2)

    service_fee_2pct = round(gross_loan * 0.02, 2)
    mri_fee = round(gross_loan * 0.007739, 2)
    net_proceeds = round(max(0.0, gross_loan - outstanding_offset - service_fee_2pct - mri_fee), 2)

    base_net_pay = current_net_take_home_pay if current_net_take_home_pay is not None else round(basic_monthly_salary * 0.72, 2)
    projected_net_pay = round(base_net_pay + replaced_amort - new_amort, 2)

    return {
        "eligible": multiplier > 0 and net_proceeds > 0,
        "basic_monthly_salary": round(basic_monthly_salary, 2),
        "ppp_years": round(ppp_years, 2),
        "salary_multiplier_months": multiplier,
        "max_loanable_entitlement": max_entitlement,
        "gross_loan_amount": gross_loan,
        "requested_term_months": term_months,
        "interest_rate_annual": annual_rate,
        "outstanding_offset": outstanding_offset,
        "service_fee_2pct": service_fee_2pct,
        "mri_fee": mri_fee,
        "estimated_net_proceeds": net_proceeds,
        "new_monthly_amortization": new_amort,
        "projected_net_take_home_pay": projected_net_pay,
        "gaa_5000_threshold_passed": projected_net_pay >= 5000.0,
        "disclaimer": OFFICIAL_TENTATIVE_DISCLAIMER,
    }


def calculate_ra8291_retirement(
    amc: float,
    ppp_years: float,
    age: int = 60,
) -> Dict[str, Any]:
    """
    Deterministically computes RA 8291 Basic Monthly Pension (BMP = 0.025 * (AMC + 700) * PPP),
    capped at 90% of AMC, plus Option 1 (60-Month Lump Sum) and Option 2 (18-Month Cash Payment).
    """
    raw_bmp = round(0.025 * (amc + 700.0) * ppp_years, 2)
    max_cap_90pct = round(amc * 0.90, 2)
    final_bmp = round(min(raw_bmp, max_cap_90pct), 2)

    opt1_lump_sum = round(final_bmp * 60, 2)
    opt2_cash = round(final_bmp * 18, 2)
    survivorship_spouse = round(final_bmp * 0.50, 2)

    return {
        "eligible_for_retirement": age >= 60 and ppp_years >= 15.0,
        "age": age,
        "amc": round(amc, 2),
        "ppp_years": round(ppp_years, 2),
        "formula_explanation": f"0.025 × (PHP {amc:,.2f} + 700) × {ppp_years} yrs = PHP {raw_bmp:,.2f}",
        "raw_bmp": raw_bmp,
        "max_bmp_cap_90pct": max_cap_90pct,
        "final_bmp": final_bmp,
        "option_1": {
            "name": "Option 1: 5-Year (60-Month) Lump Sum + Monthly Pension at Age 65 / After 5 Years",
            "five_year_lump_sum": opt1_lump_sum,
            "monthly_pension_after_5_years": final_bmp,
        },
        "option_2": {
            "name": "Option 2: 18-Month Cash Payment + Immediate Monthly Life Pension",
            "eighteen_month_cash_payment": opt2_cash,
            "immediate_monthly_pension": final_bmp,
        },
        "survivorship_spouse_monthly_pension": survivorship_spouse,
        "funeral_benefit": 30000.00,
        "disclaimer": OFFICIAL_TENTATIVE_DISCLAIMER,
    }
